import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, expect, it, vi } from 'vitest';
import { Pool } from 'pg';
const url = process.env.TEST_DATABASE_URL ?? 'postgresql://localhost:5432/canrush_site_test';
if (new URL(url).pathname !== '/canrush_site_test') throw new Error('Test DB only');
const pool = new Pool({ connectionString: url, max: 4 });
vi.mock('../src/db/pool', () => ({ getPool: () => pool }));
const api = await import('../src/lib/market');
const users = [randomUUID(), randomUUID(), randomUUID(), randomUUID()];
const [seller, buyer, stranger, lateBuyer] = users as [string, string, string, string];
const photo = { data: Buffer.from('test'), thumbnail: Buffer.from('thumb') };
let listing: string, order: string;
beforeAll(async () => {
  for (const id of users) await pool.query(`insert into "user"(id,name,email,"emailVerified","createdAt","updatedAt") values($1,'Market test',$2,true,now(),now())`, [id, id + '@example.com']);
});
afterAll(async () => { await pool.query('delete from "user" where id=any($1::text[])', [users]); await pool.end(); });
it('creates ordered listing photos and rejects self orders', async () => {
  listing = await api.createListing(seller, { title: 'Test', description: 'Test lot', city: 'Москва', price: 10000, quantity: 10, delivery: ['pickup'] }, [photo, photo]);
  expect((await api.getListing(listing))?.photos).toHaveLength(2);
  await expect(api.startOrder(seller, listing)).rejects.toThrow();
  const ids = await Promise.all([api.startOrder(buyer, listing), api.startOrder(buyer, listing)]);
  expect(ids[0]).toBe(ids[1]); order = ids[0]!;
  expect(await api.getOrder(stranger, order)).toBeNull();
  await expect(api.getMessages(stranger, order)).rejects.toThrow();
});
it('protects messages, attachments, unread markers and concurrent sends', async () => {
  await expect(api.sendMarketMessage(stranger, order, 'Intrusion', [])).rejects.toThrow();
  const attempts = await Promise.allSettled([api.sendMarketMessage(buyer, order, 'Hello', [photo]), api.sendMarketMessage(buyer, order, 'Duplicate', [photo])]);
  expect(attempts.filter(result => result.status === 'fulfilled')).toHaveLength(1);
  const messages = await api.getMessages(seller, order);
  expect(messages.items).toHaveLength(1);
  const item = messages.items[0]!;
  expect(await api.getMarketPhoto(item.photos[0]!, null, false)).toBeUndefined();
  expect(await api.getMarketPhoto(item.photos[0]!, stranger, false)).toBeUndefined();
  expect(await api.getMarketPhoto(item.photos[0]!, seller, false)).toEqual(photo.data);
  expect((await api.getOrder(seller, order))?.unread).toBe(1);
  await api.markMessagesRead(stranger, order, item.id);
  expect((await api.getOrder(seller, order))?.unread).toBe(1);
  await api.markMessagesRead(seller, order, item.id);
  expect((await api.getOrder(seller, order))?.unread).toBe(0);
});
it('allows multiple buyers, role-specific status changes and manual closure', async () => {
  const second = await api.startOrder(stranger, listing);
  await expect(api.changeOrderStatus(buyer, order, 'confirmed')).rejects.toThrow();
  await api.changeOrderStatus(seller, order, 'confirmed');
  await api.changeOrderStatus(seller, second, 'confirmed');
  await expect(api.changeOrderStatus(seller, order, 'completed')).rejects.toThrow();
  await api.changeOrderStatus(buyer, order, 'completed');
  expect((await api.getListing(listing))?.closed).toBe(false);
  await expect(api.changeOrderStatus(buyer, order, 'cancelled')).rejects.toThrow();
  await expect(api.closeListing(buyer, listing)).rejects.toThrow();
  await api.closeListing(seller, listing);
  expect((await api.getListing(listing))?.closed).toBe(true);
  expect(await api.startOrder(stranger, listing)).toBe(second);
  await expect(api.startOrder(buyer, listing)).rejects.toThrow('недоступно');
  await expect(api.startOrder(lateBuyer, listing)).rejects.toThrow('недоступно');
  await api.changeOrderStatus(stranger, second, 'cancelled');
  await expect(api.changeOrderStatus(seller, second, 'confirmed')).rejects.toThrow();
});
it('paginates history without duplicates and does not expose email display names', async () => {
  for (let index = 0; index < 55; index++) await pool.query('insert into "marketMessage"("orderId","senderId",text) values($1,$2,$3)', [order, buyer, `Message ${index}`]);
  const first = await api.getMessages(seller, order);
  const older = await api.getMessages(seller, order, first.items[0]!.id);
  expect(first.items).toHaveLength(50); expect(first.hasMore).toBe(true);
  expect(older.items).toHaveLength(6); expect(older.hasMore).toBe(false);
  expect(new Set([...older.items, ...first.items].map(message => message.id)).size).toBe(56);
  await pool.query('update "user" set name=email where id=any($1::text[])', [[seller, buyer]]);
  expect((await api.getListing(listing))?.sellerName).not.toContain('@');
  expect((await api.getOrder(buyer, order))?.sellerName).not.toContain('@');
});
it('reserves stock atomically, freezes prices and returns a reservation exactly once', async () => {
  await pool.query('update "user" set "lastMarketListingAt"=null,"lastMarketOrderAt"=null where id=any($1::text[])', [users]);
  const stockListing = await api.createListing(seller, { title: 'Stock', description: 'Single cans', city: 'Москва', price: 15050, quantity: 5, delivery: ['pickup'] }, [photo]);
  const attempts = await Promise.allSettled([api.startOrder(buyer, stockListing, 3), api.startOrder(stranger, stockListing, 3)]);
  expect(attempts.filter(result => result.status === 'fulfilled')).toHaveLength(1);
  expect((await api.getListing(stockListing))?.quantity).toBe(2);
  const winner = attempts[0]?.status === 'fulfilled' ? buyer : stranger;
  const reservation = attempts.find(result => result.status === 'fulfilled');
  if (reservation?.status !== 'fulfilled') throw new Error('Missing reservation');
  const reserved = reservation.value;
  expect(await api.startOrder(winner, stockListing, 2)).toBe(reserved);
  expect((await api.getListing(stockListing))?.quantity).toBe(2);
  expect(await api.getOrder(winner, reserved)).toMatchObject({ quantity: 3, unitPrice: 15050, price: 45150 });
  await pool.query('update "marketListing" set price=20000 where id=$1', [stockListing]);
  expect((await api.getOrder(winner, reserved))?.price).toBe(45150);
  const cancellations = await Promise.allSettled([api.changeOrderStatus(winner, reserved, 'cancelled'), api.changeOrderStatus(seller, reserved, 'cancelled')]);
  expect(cancellations.filter(result => result.status === 'fulfilled')).toHaveLength(1);
  expect((await api.getListing(stockListing))?.quantity).toBe(5);
  await pool.query('update "user" set "lastMarketOrderAt"=null where id=$1', [winner]);
  const replacement = await api.startOrder(winner, stockListing, 5);
  expect(replacement).not.toBe(reserved);
  expect((await api.getListing(stockListing))?.quantity).toBe(0);
  expect(await api.getActiveOrderId(winner, stockListing)).toBe(replacement);
  await expect(api.startOrder(lateBuyer, stockListing, 1)).rejects.toThrow('Недостаточно');
  await expect(api.startOrder(lateBuyer, stockListing, -1)).rejects.toThrow();
  await api.changeOrderStatus(seller, replacement, 'confirmed');
  await api.changeOrderStatus(winner, replacement, 'completed');
  expect((await api.getListing(stockListing))?.quantity).toBe(0);
});
it('blocks publication and messages, hides listings by blocked sellers', async () => {
  await pool.query('insert into "userBlock"("userId") values($1)', [seller]);
  await expect(api.sendMarketMessage(seller, order, 'Blocked', [])).rejects.toThrow();
  await expect(api.createListing(seller, { title: 'Test', description: 'Test', city: 'Москва', price: 100, quantity: 1, delivery: ['pickup'] }, [photo])).rejects.toThrow();
  expect(await api.getListing(listing)).toBeNull();
  expect(await api.getListing(listing, seller)).not.toBeNull();
});

it('removes only owned archived listings while preserving orders and admin review access', async () => {
  await pool.query('delete from "userBlock" where "userId"=$1',[seller]);
  await expect(api.deleteArchivedListing(buyer, listing)).rejects.toThrow();
  const active = await pool.query('insert into "marketListing" ("sellerId",title,description,city,price,delivery,quantity) values ($1,\'Active\',\'Description\',\'Москва\',100,ARRAY[\'pickup\'],1) returning id',[seller]);
  await expect(api.deleteArchivedListing(seller, active.rows[0].id)).rejects.toThrow();
  const photoId = (await api.getListing(listing))!.photos[0]!;
  await api.deleteArchivedListing(seller, listing);
  expect(await api.getListing(listing, seller)).toBeNull();
  expect((await api.getListings(1,seller,true)).items.some(item=>item.id===listing)).toBe(false);
  expect(await api.getOrder(buyer,order)).not.toBeNull();
  expect((await api.getMessages(buyer,order)).items.length).toBeGreaterThan(0);
  expect(await api.getMarketPhoto(photoId,null,false)).toBeUndefined();
  expect(await api.getListing(listing,stranger,true)).not.toBeNull();
  await pool.query('insert into "siteAdmin"(email) values ($1)',[stranger+'@example.com']);
  try {
    expect(await api.getMarketPhoto(photoId,stranger,false)).toEqual(photo.data);
    const { getAdminDashboardData } = await import('../src/lib/admin-dashboard-data');
    expect((await getAdminDashboardData(stranger+'@example.com','market')).market).toEqual([]);
    expect((await getAdminDashboardData(seller+'@example.com','market')).market.some(item=>item.id===listing && item.deletedAt)).toBe(true);
  } finally { await pool.query('delete from "siteAdmin" where email=$1',[stranger+'@example.com']); }
});
